### ISSUE TITLE
Some advises for Find method

### ISSUE THREAD

**Issue by PodstDO** [davidkin/DavidRealisation#24]
You may add `return undefined;` if there is found nothing and rewrite Your method:
```
 find(callback, thisArg) {   
   for (let i = 0; i < this.length; i++) {   
     if (callback.call(thisArg, this[i], i, this)) { 
       return this[i]; 
     } 
   } 
  return undefined;
 } 
```
https://github.com/davidkin/DavidRealisation/blob/ca336c8d50c4805e013c0fb1691a6d02361a4353/src/index.js#L174-L184

**Comment by motifej** [comment]
by default every function return ``` undefined```
